### ISSUE TITLE
大佬，这个是提示是什么原因呢

### ISSUE THREAD

**Issue by LINXIANN** [jiasai007/wxyd#1]
![IMG_5720](https://user-images.githubusercontent.com/109235463/223540228-0ddb71a9-a199-4bdd-9a0c-816be7da1ffa.jpeg)

**Comment by jiasai007** [comment]
删了脚本 重新拉库 试试

**Comment by LINXIANN** [comment]
> 删了微信阅读脚本 重新拉库下载 试试

重新试过了，还是提示同样的问题
